<a href="https://colab.research.google.com/github/paulinaeb/IDaSec-project/blob/exp3/after_evasion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone --branch exp4 https://github.com/paulinaeb/IDaSec-project.git

Cloning into 'IDaSec-project'...
remote: Enumerating objects: 342, done.
remote: Counting objects: 100% (176/176), done.
remote: Compressing objects: 100% (144/144), done.
remote: Total 342 (delta 90), reused 104 (delta 27), pack-reused 166 (from 1)
Receiving objects: 100% (342/342), 31.79 MiB | 14.45 MiB/s, done.
Resolving deltas: 100% (150/150), done.

In [2]:
import os
import pandas as pd


## Enron1

In [3]:
# Path to the dataset folder
dataset_path = "IDaSec-project/dataset/enron1"

# List all subfolders in dataset
subfolders = [f.name for f in os.scandir(dataset_path) if f.is_dir()]
print("available datasets:", subfolders)

enron1_charswap_path = dataset_path + "/charswap"
enron1_homoglyph_path = dataset_path + "/homoglyph"
enron1_spacing_path = dataset_path + "/spacing"

enron1_charswap_files = os.listdir(enron1_charswap_path)
print(f"\nFiles in '{enron1_charswap_path}': {enron1_charswap_files}")

enron1_homoglyph_files = os.listdir(enron1_homoglyph_path)
print(f"\nFiles in '{enron1_homoglyph_path}': {enron1_homoglyph_files}")

enron1_spacing_files = os.listdir(enron1_spacing_path)
print(f"\nFiles in '{enron1_spacing_path}': {enron1_spacing_files}")

available datasets: ['spacing', 'charswap', 'homoglyph']

Files in 'IDaSec-project/dataset/enron1/charswap': ['enron1_test_with_charswap.csv', 'enron1_train_with_charswap.csv', 'enron1_val_with_charswap.csv']

Files in 'IDaSec-project/dataset/enron1/homoglyph': ['enron1_train_homoglyph.csv', 'enron1_test_homoglyph.csv', 'enron1_val_homoglyph.csv']

Files in 'IDaSec-project/dataset/enron1/spacing': ['enron1_test_spacing.csv', 'enron1_val_spacing.csv', 'enron1_train_spacing.csv']

### Enron1-charswap

In [4]:
enron1_charswap_train = pd.read_csv(enron1_charswap_path + "/enron1_test_with_charswap.csv")
enron1_charswap_test = pd.read_csv(enron1_charswap_path + "/enron1_train_with_charswap.csv")
enron1_charswap_val = pd.read_csv(enron1_charswap_path + "/enron1_val_with_charswap.csv")

In [5]:
enron1_charswap_train.head()

,email,target,email_charswapped,was_augmented
0,Subject: unify / sitara enhancements i am comp...,ham,Subject: unify / sitara enhancements i am comp...,False
1,Subject: weekend activity dated : june 2 thru ...,ham,Subject: weekend activity dated : june 2 thru ...,False
2,Subject: re : tittletattle secrets dn ' t ie n...,spam,"[""Subject: re: tittletattle secrets dn ' t ie ...",True
3,"Subject: deal id 109475 daren , the above deal...",ham,"Subject: deal id 109475 daren , the above deal...",False
4,Subject: weekend entertainment alpha male plus...,spam,['Subject: wekened etneratinmnet aplha amle pl...,True

### Enron1-homoglyph

In [6]:
enron1_homoglyph_train = pd.read_csv(enron1_homoglyph_path + "/enron1_train_homoglyph.csv")
enron1_homoglyph_test = pd.read_csv(enron1_homoglyph_path + "/enron1_test_homoglyph.csv")
enron1_homoglyph_val = pd.read_csv(enron1_homoglyph_path + "/enron1_val_homoglyph.csv")

In [7]:
enron1_homoglyph_train.head()

,email,target,email_homoglyph
0,"Subject: prom dress shopping hi , just wanted ...",ham,"Subject: prom dress shopping hi , just wanted ..."
1,"Subject: hi agaain hello , welcome to pharm la...",spam,"𝕾𝓾bjec𝕥∶ hi aga𝕒in hell𝙤 , welcome to p𝒉𝔞ꭈm la..."
2,Subject: feedback monitor error - meter 984132...,ham,Subject: feedback monitor error - meter 984132...
3,Subject: instructions to remove spyware / adwa...,spam,𝘚ubｊ𝕖ctː instructions to r𝖾move sｐℽware / adwa...
4,Subject: acrobat pro 7 . 0 $ 69 . 95 xp pro op...,spam,Sꭒb𝒋𝙚c𝙩︰ a𝕔roba𝘵 𝗉r𝝄 7 𝅭 0 $ 69 . 95 x𝝔 pro op...

### Enron1-spacing

In [8]:
enron1_spacing_train = pd.read_csv(enron1_spacing_path + "/enron1_train_spacing.csv")
enron1_spacing_test = pd.read_csv(enron1_spacing_path + "/enron1_test_spacing.csv")
enron1_spacing_val = pd.read_csv(enron1_spacing_path + "/enron1_val_spacing.csv")

In [9]:
enron1_spacing_train.head()

,email,target,email_spaced
0,"Subject: prom dress shopping hi , just wanted ...",ham,"Subject: prom dress shopping hi , just wanted ..."
1,"Subject: hi agaain hello , welcome to pharm la...",spam,"Subject: hi agaain he llo , w e l c o m e to p..."
2,Subject: feedback monitor error - meter 984132...,ham,Subject: feedback monitor error - meter 984132...
3,Subject: instructions to remove spyware / adwa...,spam,Subject: i n s t r u c t i o n s to r e m o v ...
4,Subject: acrobat pro 7 . 0 $ 69 . 95 xp pro op...,spam,Subject: a c r o b a t p r o 7 . 0 $ 69 . 95 x...

In [16]:
enron1_spacing_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3196 entries, 0 to 3195
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   email         3196 non-null   object
 1   target        3196 non-null   object
 2   email_spaced  3196 non-null   object
dtypes: object(3)
memory usage: 75.0+ KB

## adversarial

In [13]:
enron1_light_adversarial_train_path = "IDaSec-project/dataset/enron1/enron1_train_lightadversarial.csv"
enron1_light_adversarial_val_path = "IDaSec-project/dataset/enron1/enron1_val_lightadversarial.csv"
enron1_light_adversarial_test_path = "IDaSec-project/dataset/enron1/enron1_test_lightadversarial.csv"

enron1_light_adversarial_train = pd.read_csv(enron1_light_adversarial_train_path)
enron1_light_adversarial_val = pd.read_csv(enron1_light_adversarial_val_path)
enron1_light_adversarial_test = pd.read_csv(enron1_light_adversarial_test_path)

In [14]:
enron1_light_adversarial_train.head()

,original,adversarial_light,target
0,"Subject: prom dress shopping hi , just wanted ...","Subject: prom dress shopping hi , just wanted ...",ham
1,"Subject: hi agaain hello , welcome to pharm la...","Subject: hi agaain hello , welcome to pharm la...",spam
2,Subject: feedback monitor error - meter 984132...,Subject: feedback monitor error - meter 984132...,ham
3,Subject: instructions to remove spyware / adwa...,Subject: instructions to remove $pyw@r3 / adwa...,spam
4,Subject: acrobat pro 7 . 0 $ 69 . 95 xp pro op...,Subject: acrobat pr0 7 . 0 $ 69 . 95 xp pro op...,spam

In [15]:
enron1_light_adversarial_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3196 entries, 0 to 3195
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   original           3196 non-null   object
 1   adversarial_light  3196 non-null   object
 2   target             3196 non-null   object
dtypes: object(3)
memory usage: 75.0+ KB